# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

name: Build Devcontainer

on:
  workflow_dispatch

jobs:
  build_devcontainer:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      output1: ${{ steps.filter.outputs.devcontainer }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HDML_FOUNDATION_DOCKER_NAME }}
          password: ${{ secrets.HDML_FOUNDATION_DOCKER }}
      - name: Replace devcontainer.json to CI version
        run: |
          rm .devcontainer/devcontainer.json
          mv .devcontainer/devcontainer_ci.json .devcontainer/devcontainer.json
      - name: Build and push DevContainer image
        uses: devcontainers/ci@v0.3
        with:
          push: always
          imageName: hdio/hdml-utilities-dev
          cacheFrom: hdio/hdml-utilities-dev