# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

name: Main Branch

on:
  push:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/main.yml'
      - '.github/workflows/release.yml'
      - '.eslintrc.js'
      - '.gitignore'
      - '.jestrc.js'
      - 'package-lock.json'
      - 'package.json'
      - 'README.md'
      - 'packages/**'
      - 'tsconfig/**'
    branches:
      - 'main'
  pull_request:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/main.yml'
      - '.github/workflows/release.yml'
      - '.eslintrc.js'
      - '.gitignore'
      - '.jestrc.js'
      - 'package-lock.json'
      - 'package.json'
      - 'README.md'
      - 'packages/**'
      - 'tsconfig/**'

jobs:
  build_devcontainer:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      output1: ${{ steps.filter.outputs.devcontainer }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HDML_FOUNDATION_DOCKER_NAME }}
          password: ${{ secrets.HDML_FOUNDATION_DOCKER }}
      - name: Replace devcontainer.json to CI version
        run: |
          rm .devcontainer/devcontainer.json
          mv .devcontainer/devcontainer_ci.json .devcontainer/devcontainer.json
      # if
      - name: Check for the DevContainer changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            devcontainer:
              - '.devcontainer/Dockerfile'
      # then
      - name: Build and push DevContainer image
        if: steps.filter.outputs.devcontainer == 'true'
        uses: devcontainers/ci@v0.3
        with:
          push: always
          imageName: hdio/hdml-utilities-dev
          cacheFrom: hdio/hdml-utilities-dev
      # else
      - name: No Changes Message
        if: steps.filter.outputs.devcontainer != 'true'
        run: echo "DevContainer was not changed"
  
  build_ts_library:
    runs-on: ubuntu-latest
    needs: build_devcontainer
    timeout-minutes: 5
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HDML_FOUNDATION_DOCKER_NAME }}
          password: ${{ secrets.HDML_FOUNDATION_DOCKER }}
      - name: Replace devcontainer.json to CI version
        run: |
          rm .devcontainer/devcontainer.json
          mv .devcontainer/devcontainer_ci.json .devcontainer/devcontainer.json
      - name: Build TS library
        uses: devcontainers/ci@v0.3
        with:
          push: never
          cacheFrom: hdio/hdml-utilities-dev
          runCmd: |
            npm ci
            npm run build --workspaces